### ISSUE TITLE
zeromq broker support

### ISSUE THREAD

**Issue by shicky** [shicky/gocelery#16]
Celery has experimental support for [ZeroMQ broker](http://zeromq.org/).
ZeroMQ is brokerless high performance message queue that outperforms others.

**Comment by ask** [comment]
Celery doesn't have support for this anymore, it was more of an experiment but I'm not sure it ever worked properly.

ZeroMQ is definitely high performance, but it's unfair to compare that to RabbitMQ since 0mq doesn't actually implement the same features (the broker part is not something you can easily let go of if you need delivery guarantees).

Using ZeroMQ for Celery would involve designing a persistency layer (unless you only want to support transient messaging, which is certainly useful for some applications), service discovery etc.

If you find a pattern that works then we'd definitely want to have that in the Python version also.

Btw, I'm very impressed with your project, really great work!  Have you looked at the new message protocol in Celery 4? http://docs.celeryproject.org/en/master/internals/protocol.html#task-messages
